# permissions for end users to edit petclinichelms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: petclinichelm-editor-role
rules:
- apiGroups:
  - demo.helm.op.com
  resources:
  - petclinichelms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.helm.op.com
  resources:
  - petclinichelms/status
  verbs:
  - get
