# permissions for end users to view petclinichelms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: petclinichelm-viewer-role
rules:
- apiGroups:
  - demo.helm.op.com
  resources:
  - petclinichelms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.helm.op.com
  resources:
  - petclinichelms/status
  verbs:
  - get
